route: 
  #hello-world: helloWorld
  helloWorld: helloWorld
  helloworld: helloWorld
  messages:
  - Mike
  - Joe
  - Lisa
  duration: 600
  
logging:
  level:
    org:
      springframework:
        data:
          jpa: DEBUG
          security: INFO
  
         
spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE    
    platform: h2
     

  jpa:
    generate-ddl: true
    show-sql: true

  hibernate:
    ddl-auto: create-drop    

  h2:
    console:
      enabled: true
      path: /h2-console
      
  profiles:
    active: noAuthentification


security:
  basic:
    enabled: false 
    
    
    
  devtools:
    restart:
      log-condition-evaluation-delta: true